"""Add interview, turn, and feedback models

Revision ID: 45407303f5dd
Revises: 
Create Date: 2026-03-12 19:31:58.085580+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision = '45407303f5dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviews',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who owns this interview'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Current interview state'),
    sa.Column('cv_raw_text', sa.Text(), nullable=True, comment='Original extracted CV text'),
    sa.Column('cv_analysis', sa.JSON(), nullable=True, comment='Structured CV analysis from AI (skills, experience, etc.)'),
    sa.Column('jd_raw_text', sa.Text(), nullable=True, comment='Original job description text'),
    sa.Column('jd_analysis', sa.JSON(), nullable=True, comment='Structured JD analysis from AI (requirements, level, etc.)'),
    sa.Column('interview_config', sa.JSON(), nullable=True, comment='Interview settings (phases, question counts, difficulty)'),
    sa.Column('target_role', sa.String(length=255), nullable=True, comment='Job title extracted from JD'),
    sa.Column('target_company', sa.String(length=255), nullable=True, comment='Company name if specified'),
    sa.Column('session_state', sa.JSON(), nullable=True, comment='Current interview session state (for crash recovery)'),
    sa.Column('current_phase', sa.String(length=20), nullable=True, comment='Current interview phase'),
    sa.Column('current_turn', sa.Integer(), nullable=False, comment='Current turn number (0 = not started)'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='When the interview was completed'),
    sa.Column('total_duration_seconds', sa.Float(), nullable=True, comment='Total interview duration in seconds'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='When this record was last updated'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interview_completed', 'interviews', ['completed_at'], unique=False)
    op.create_index('idx_interview_role', 'interviews', ['target_role'], unique=False)
    op.create_index('idx_interview_user_status', 'interviews', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_interviews_status'), 'interviews', ['status'], unique=False)
    op.create_index(op.f('ix_interviews_target_role'), 'interviews', ['target_role'], unique=False)
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('interview_id', sa.UUID(), nullable=False, comment='Interview this feedback belongs to'),
    sa.Column('overall_score', sa.Float(), nullable=False, comment='Overall interview score (0-100)'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Brief summary of performance'),
    sa.Column('strengths', sa.JSON(), nullable=False, comment='List of identified strengths with evidence'),
    sa.Column('weaknesses', sa.JSON(), nullable=False, comment='List of identified weaknesses with evidence'),
    sa.Column('suggestions', sa.JSON(), nullable=False, comment='Actionable improvement suggestions'),
    sa.Column('phase_scores', sa.JSON(), nullable=False, comment='Score breakdown by interview phase'),
    sa.Column('skill_assessment', sa.JSON(), nullable=True, comment='Assessment of specific skills mentioned in JD'),
    sa.Column('detailed_analysis', sa.Text(), nullable=True, comment='Full narrative feedback analysis'),
    sa.Column('generation_metadata', sa.JSON(), nullable=True, comment='Metadata about feedback generation (AI model, tokens used, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='When this record was last updated'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_created', 'feedback', ['created_at'], unique=False)
    op.create_index('idx_feedback_score', 'feedback', ['overall_score'], unique=False)
    op.create_index(op.f('ix_feedback_interview_id'), 'feedback', ['interview_id'], unique=True)
    op.create_table('turns',
    sa.Column('interview_id', sa.UUID(), nullable=False, comment='Interview this turn belongs to'),
    sa.Column('turn_number', sa.Integer(), nullable=False, comment='Sequential turn number (1, 2, 3...)'),
    sa.Column('phase', sa.String(length=20), nullable=False, comment='Interview phase when this turn occurred'),
    sa.Column('ai_question', sa.Text(), nullable=False, comment="The AI's question to the candidate"),
    sa.Column('user_answer', sa.Text(), nullable=True, comment="Candidate's transcribed answer"),
    sa.Column('evaluation', sa.JSON(), nullable=True, comment='AI evaluation of the answer (relevance, depth, clarity)'),
    sa.Column('duration_seconds', sa.Float(), nullable=True, comment='How long the candidate took to answer'),
    sa.Column('difficulty_level', sa.Float(), nullable=True, comment='Question difficulty (0.0 = easy, 1.0 = hard)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='When this record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='When this record was last updated'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_turn_interview_number', 'turns', ['interview_id', 'turn_number'], unique=False)
    op.create_index('idx_turn_phase', 'turns', ['phase'], unique=False)
    op.create_index('idx_turn_unique', 'turns', ['interview_id', 'turn_number'], unique=True)
    op.create_index(op.f('ix_turns_interview_id'), 'turns', ['interview_id'], unique=False)
    op.create_index(op.f('ix_turns_phase'), 'turns', ['phase'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_turns_phase'), table_name='turns')
    op.drop_index(op.f('ix_turns_interview_id'), table_name='turns')
    op.drop_index('idx_turn_unique', table_name='turns')
    op.drop_index('idx_turn_phase', table_name='turns')
    op.drop_index('idx_turn_interview_number', table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_feedback_interview_id'), table_name='feedback')
    op.drop_index('idx_feedback_score', table_name='feedback')
    op.drop_index('idx_feedback_created', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_target_role'), table_name='interviews')
    op.drop_index(op.f('ix_interviews_status'), table_name='interviews')
    op.drop_index('idx_interview_user_status', table_name='interviews')
    op.drop_index('idx_interview_role', table_name='interviews')
    op.drop_index('idx_interview_completed', table_name='interviews')
    op.drop_table('interviews')
    # ### end Alembic commands ###